### ISSUE TITLE
which version of pytorch and pytorch_quantization?

### ISSUE THREAD

**Issue by avBuffer** [LemonWang0110/YOLOv8_PTQ#1]
1>  python quant_ptq.py 

2> error log:
Traceback (most recent call last):
  File "quant_ptq.py", line 27, in <module>
    import quant_utils as quant
  File "/home/work/YOLOv8_PTQ/quant_utils.py", line 8, in <module>
    from pytorch_quantization import nn as quant_nn
  File "/home/anaconda3/envs/YOLO/lib/python3.8/site-packages/pytorch_quantization/__init__.py", line 20, in <module>
    from .quant_modules import *
  File "/home/anaconda3/envs/YOLO/lib/python3.8/site-packages/pytorch_quantization/quant_modules.py", line 23, in <module>
    from pytorch_quantization import nn as quant_nn
  File "/home/anaconda3/envs/YOLO/lib/python3.8/site-packages/pytorch_quantization/nn/__init__.py", line 19, in <module>
    from pytorch_quantization.nn.modules.tensor_quantizer import *
  File "/home/anaconda3/envs/YOLO/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 24, in <module>
    from pytorch_quantization.tensor_quant import QuantDescriptor, tensor_quant, fake_tensor_quant, scaled_e4m3
  File "/home/anaconda3/envs/YOLO/lib/python3.8/site-packages/pytorch_quantization/tensor_quant.py", line 28, in <module>
    from pytorch_quantization import cuda_ext
ImportError: /home/anaconda3/envs/YOLO/lib/python3.8/site-packages/pytorch_quantization/cuda_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by LemonWang0110** [comment]
@avBuffer I apologize for getting back to you so late！You can refer to this solution： [reinstall pytorch_quantization.](https://github.com/NVIDIA/TensorRT/issues/3381#issuecomment-1765914385)  An additional note is that using this solution requires that the installed CUDA version of Pytorch must match the locally installed CUDA version!
